In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [53]:
df = pd.read_csv("Hitters.csv")
df.head(10)

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   
6    185    37      1    23    8     21      2     214     42       1     30   
7    298    73      0    24   24      7      3     509    108       0     41   
8    323    81      6    26   32      8      2     341     86       6     32   
9    401    92     17    49   66     65     13    5206   1332     253    784   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
0    29      14      A        E      446       33      20     NaN         A  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A  
6     9      24      N        E       76      127       7    70.0         A  
7    37      12      A        W      121      283       9   100.0         A  
8    34       8      N        W      143      290      19    75.0         N  
9   890     866      A        E        0        0       0  1100.0         A

In [54]:
df.describe().T

count         mean          std   min     25%     50%      75%  \
AtBat    322.0   380.928571   153.404981  16.0  255.25   379.5   512.00   
Hits     322.0   101.024845    46.454741   1.0   64.00    96.0   137.00   
HmRun    322.0    10.770186     8.709037   0.0    4.00     8.0    16.00   
Runs     322.0    50.909938    26.024095   0.0   30.25    48.0    69.00   
RBI      322.0    48.027950    26.166895   0.0   28.00    44.0    64.75   
Walks    322.0    38.742236    21.639327   0.0   22.00    35.0    53.00   
Years    322.0     7.444099     4.926087   1.0    4.00     6.0    11.00   
CAtBat   322.0  2648.683230  2324.205870  19.0  816.75  1928.0  3924.25   
CHits    322.0   717.571429   654.472627   4.0  209.00   508.0  1059.25   
CHmRun   322.0    69.490683    86.266061   0.0   14.00    37.5    90.00   
CRuns    322.0   358.795031   334.105886   1.0  100.25   247.0   526.25   
CRBI     322.0   330.118012   333.219617   0.0   88.75   220.5   426.25   
CWalks   322.0   260.239130   267.058085   0.0   67.25   170.5   339.25   
PutOuts  322.0   288.937888   280.704614   0.0  109.25   212.0   325.00   
Assists  322.0   106.913043   136.854876   0.0    7.00    39.5   166.00   
Errors   322.0     8.040373     6.368359   0.0    3.00     6.0    11.00   
Salary   263.0   535.925882   451.118681  67.5  190.00   425.0   750.00   

             max  
AtBat      687.0  
Hits       238.0  
HmRun       40.0  
Runs       130.0  
RBI        121.0  
Walks      105.0  
Years       24.0  
CAtBat   14053.0  
CHits     4256.0  
CHmRun     548.0  
CRuns     2165.0  
CRBI      1659.0  
CWalks    1566.0  
PutOuts   1378.0  
Assists    492.0  
Errors      32.0  
Salary    2460.0

In [55]:
median = df["Salary"].median()
median


425.0

In [56]:
df["Salary"].fillna(median, inplace = True)

In [57]:
df["Salary"]

0       425.0
1       475.0
2       480.0
3       500.0
4        91.5
        ...  
317     700.0
318     875.0
319     385.0
320     960.0
321    1000.0
Name: Salary, Length: 322, dtype: float64

In [58]:
df.isna().any()

AtBat        False
Hits         False
HmRun        False
Runs         False
RBI          False
Walks        False
Years        False
CAtBat       False
CHits        False
CHmRun       False
CRuns        False
CRBI         False
CWalks       False
League       False
Division     False
PutOuts      False
Assists      False
Errors       False
Salary       False
NewLeague    False
dtype: bool

In [59]:
dum = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
dum

League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
0           1         0           1           0            1            0
1           0         1           0           1            0            1
2           1         0           0           1            1            0
3           0         1           1           0            0            1
4           0         1           1           0            0            1
..        ...       ...         ...         ...          ...          ...
317         0         1           1           0            0            1
318         1         0           1           0            1            0
319         1         0           0           1            1            0
320         1         0           1           0            1            0
321         1         0           0           1            1            0

[322 rows x 6 columns]

In [60]:
dum = dum.drop(["League_N", "Division_W", "NewLeague_N"], axis = 1)

In [61]:
df = df.drop(['League', 'Division', 'NewLeague'], axis = 1)

In [62]:
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks  PutOuts  Assists  Errors  Salary  
0    29      14      446       33      20   425.0  
1   414     375      632       43      10   475.0  
2   266     263      880       82      14   480.0  
3   838     354      200       11       3   500.0  
4    46      33      805       40       4    91.5

In [63]:
df = pd.concat([df, dum], axis = 1)

In [64]:
df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks  PutOuts  Assists  Errors  Salary  League_A  Division_E  \
0    29      14      446       33      20   425.0         1           1   
1   414     375      632       43      10   475.0         0           0   
2   266     263      880       82      14   480.0         1           0   
3   838     354      200       11       3   500.0         0           1   
4    46      33      805       40       4    91.5         0           1   

   NewLeague_A  
0            1  
1            0  
2            1  
3            0  
4            0

In [65]:
df.shape

(322, 20)

In [67]:
y = df["Salary"]
y.head()

0    425.0
1    475.0
2    480.0
3    500.0
4     91.5
Name: Salary, dtype: float64

In [69]:
X = df.drop(["Salary"],axis = 1)
X.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks  PutOuts  Assists  Errors  League_A  Division_E  NewLeague_A  
0    29      14      446       33      20         1           1            1  
1   414     375      632       43      10         0           0            0  
2   266     263      880       82      14         1           0            1  
3   838     354      200       11       3         0           1            0  
4    46      33      805       40       4         0           1            0

In [70]:
X.shape

(322, 19)

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [73]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale 
pca = PCA()

In [74]:
X_reduced_train = pca.fit_transform(scale(X_train))

In [83]:
X_reduced_train[:3, :]

array([[-3.36551771,  1.21003662,  1.22926644, -0.74547772, -0.65314274,
         0.9257515 ,  0.66213237, -0.01356454, -0.04357466,  0.09455084,
         0.05979404,  0.13253486, -0.04024277,  0.13113351, -0.07988756,
        -0.03225038,  0.00974507,  0.02317892, -0.0134017 ],
       [ 1.09627549, -0.69509259, -1.16313395,  0.43584495,  0.7513433 ,
        -0.4441731 , -1.27087342, -0.61333988, -1.14295374,  0.04426474,
         0.07936983, -0.21011625, -0.32500746,  0.12034978,  0.05603354,
        -0.03721207, -0.23170665, -0.10940498, -0.05584267],
       [ 2.71343464,  0.67775939, -0.7308127 ,  0.36371288,  1.32572819,
         2.23145923, -1.37396914,  0.44212734, -0.3157019 , -0.22317277,
        -0.02307872, -0.04882191, -0.04313589, -0.03857827,  0.11055652,
         0.03184602,  0.33682819, -0.02445217,  0.09046426]])

In [85]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [86]:
pcr_model = lm.fit(X_reduced_train, y_train)

In [87]:
pcr_model.intercept_

506.8279395348837

In [88]:
pcr_model.coef_

array([  76.40817399,   -7.93317883,   19.73685954,  -32.033831  ,
        -51.52375722,   56.33893165,  -15.40904948,   -6.9481073 ,
         10.1071139 ,   30.87515737,   82.37237048,   -8.29234957,
         90.94389612, -268.85264366,  -92.01271989,  378.96466254,
       -317.65004837, -513.59408129,  128.82687233])

In [89]:
y_pred = pcr_model.predict(X_reduced_train)

In [90]:
y_pred[:5]

array([309.70956693, 558.81711924, 672.20234941, 508.01309714,
       448.24429306])

In [91]:
y_train[:5]

66     425.0
199    425.0
18     425.0
186    300.0
153    100.0
Name: Salary, dtype: float64

In [93]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_train, y_pred))

291.4605697117985