In [78]:
import seaborn as sns
diamonds = sns.load_dataset('diamonds')
diamonds = diamonds.select_dtypes(include = ['float64', 'int64']) 
df = diamonds.copy()
df = df.dropna()
df.head()

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [79]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

In [80]:
clf = LocalOutlierFactor(n_neighbors = 20, contamination = 0.1)

In [81]:
clf.fit_predict(df)

array([-1, -1, -1, ...,  1,  1,  1])

In [82]:
df_scores = clf.negative_outlier_factor_

In [94]:
np.sort(df_scores)[:20]

array([-8.60430658, -8.20889984, -5.86084355, -4.98415175, -4.81502092,
       -4.81502092, -4.61522833, -4.37081214, -4.29842288, -4.10492387,
       -4.0566648 , -4.01831733, -3.94882806, -3.82378797, -3.80135297,
       -3.75680919, -3.65947378, -3.59249261, -3.55564138, -3.47157375])

In [95]:
esik_deger = np.sort(df_scores)[15]

In [96]:
df_aykiri = df_scores < esik_deger

In [97]:
df_aykiri

array([ True,  True,  True, ..., False, False, False])

In [98]:
new= df[df_aykiri]

In [99]:
new

carat  depth  table  price     x     y     z
0    0.23   61.5   55.0    326  3.95  3.98  2.43
1    0.21   59.8   61.0    326  3.89  3.84  2.31
2    0.23   56.9   65.0    327  4.05  4.07  2.31
3    0.29   62.4   58.0    334  4.20  4.23  2.63
4    0.31   63.3   58.0    335  4.34  4.35  2.75
5    0.24   62.8   57.0    336  3.94  3.96  2.48
6    0.24   62.3   57.0    336  3.95  3.98  2.47
7    0.26   61.9   55.0    337  4.07  4.11  2.53
8    0.22   65.1   61.0    337  3.87  3.78  2.49
9    0.23   59.4   61.0    338  4.00  4.05  2.39
10   0.30   64.0   55.0    339  4.25  4.28  2.73
11   0.23   62.8   56.0    340  3.93  3.90  2.46
12   0.22   60.4   61.0    342  3.88  3.84  2.33
13   0.31   62.2   54.0    344  4.35  4.37  2.71
14   0.20   60.2   62.0    345  3.79  3.75  2.27