In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [4]:
b = np.arange(0,10)

In [7]:
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a = np.array([[1,2,3,4],
              [1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [16]:
c = np.concatenate((a,a),axis = 1)

In [17]:
c

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4]])