In [1]:
import numpy as np

In [11]:
arr = np.random.randint(0,10,(1,5))

In [12]:
arr

array([[2, 0, 4, 6, 4]])

In [22]:
a = arr[0:1,2:5]
a

array([[4, 6, 4]])

ilk : satırı temsil eder ikinci : sütunu temsil eder.

In [24]:
arr = np.random.randint(0,10,(3,5))
arr

array([[2, 1, 6, 6, 7],
       [3, 5, 6, 9, 7],
       [7, 6, 6, 3, 4]])

In [25]:
a = arr[0:2,1:3]
a

array([[1, 6],
       [5, 6]])

In [27]:
a = a*2
a

array([[ 4, 24],
       [20, 24]])

In [28]:
arr

array([[2, 1, 6, 6, 7],
       [3, 5, 6, 9, 7],
       [7, 6, 6, 3, 4]])

# Fancy 

In [29]:
getir = [1,3,4]

In [33]:
c = arr[0,getir]
c

array([1, 6, 7])