# number generation tecniques

In [1]:
import numpy as np

In [7]:
np.zeros((1,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

We created a matrix consisting of 2 rows and 4 columns which is can change to int with dtype argument.

In [9]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.random.randint(0,10,(3,3))

array([[2, 1, 1],
       [1, 5, 3],
       [9, 8, 1]])

In [17]:
np.random.normal(10,4,(3,3))

array([[ 8.79979886, 14.79269331,  7.83909639],
       [ 6.68079845, 11.40555416, 10.12984291],
       [12.26211427,  9.54051635, 14.34977518]])

ortalaması 10 standart sapması 4 olan 3 3 bir matrix luşturduk