In [1]:
import numpy as np

In [2]:
x = np.array([1,2,4,57,76,74,3])

In [4]:
a,b,c = np.split(x,[3,5])
a

array([1, 2, 4])

In [5]:
b

array([57, 76])

In [6]:
c

array([74,  3])

In [8]:
x = np.array([[1,2,4,57,76,74,3], [3,42,5,22,33,4,56]])

In [22]:
a,b = np.vsplit(x, [1])

In [23]:
a

array([[ 1,  2,  4, 57, 76, 74,  3]])

In [24]:
b

array([[ 3, 42,  5, 22, 33,  4, 56]])

In [25]:
a,b = np.hsplit(x, [3])

In [26]:
a

array([[ 1,  2,  4],
       [ 3, 42,  5]])

In [27]:
b

array([[57, 76, 74,  3],
       [22, 33,  4, 56]])