In [1]:
import numpy as np

In [2]:
pop = np.random.randint(0,80,10000)

In [7]:
pop[0:10]

array([60, 30, 37, 54, 11,  3,  6, 43, 55, 29])

In [28]:
np.random.seed(110)
ex = np.random.choice(pop, 100)

In [29]:
ex

array([18, 60, 43, 54, 19, 30, 19, 12, 26, 67, 68, 41, 30, 47, 61, 43, 75,
       29, 64, 52, 44, 33, 13, 73, 65, 36, 78, 72, 54, 36, 18, 30, 71, 10,
       28, 74,  1, 16, 56, 51, 76,  1, 50, 38, 64, 35, 28, 24, 17, 11,  7,
       53, 22, 49, 68,  4, 21, 40,  2, 63, 66,  5, 14, 73, 70, 41, 46, 41,
       60, 49,  7, 19, 14, 68, 51,  0, 32, 39, 74, 13, 60, 36, 36, 50, 73,
       28,  0,  7, 60, 61, 58, 70, 30, 46, 58, 64, 78, 13, 15,  3])

In [30]:
ex

array([18, 60, 43, 54, 19, 30, 19, 12, 26, 67, 68, 41, 30, 47, 61, 43, 75,
       29, 64, 52, 44, 33, 13, 73, 65, 36, 78, 72, 54, 36, 18, 30, 71, 10,
       28, 74,  1, 16, 56, 51, 76,  1, 50, 38, 64, 35, 28, 24, 17, 11,  7,
       53, 22, 49, 68,  4, 21, 40,  2, 63, 66,  5, 14, 73, 70, 41, 46, 41,
       60, 49,  7, 19, 14, 68, 51,  0, 32, 39, 74, 13, 60, 36, 36, 50, 73,
       28,  0,  7, 60, 61, 58, 70, 30, 46, 58, 64, 78, 13, 15,  3])

In [31]:
np.random.seed(110)

ex = np.random.choice(pop, 100)

In [32]:
ex

array([18, 60, 43, 54, 19, 30, 19, 12, 26, 67, 68, 41, 30, 47, 61, 43, 75,
       29, 64, 52, 44, 33, 13, 73, 65, 36, 78, 72, 54, 36, 18, 30, 71, 10,
       28, 74,  1, 16, 56, 51, 76,  1, 50, 38, 64, 35, 28, 24, 17, 11,  7,
       53, 22, 49, 68,  4, 21, 40,  2, 63, 66,  5, 14, 73, 70, 41, 46, 41,
       60, 49,  7, 19, 14, 68, 51,  0, 32, 39, 74, 13, 60, 36, 36, 50, 73,
       28,  0,  7, 60, 61, 58, 70, 30, 46, 58, 64, 78, 13, 15,  3])

In [33]:
ex.mean()

40.18

In [34]:
pop.mean()

39.4617

## betimsel istatistik

In [35]:
!pip install researchpy 
import researchpy as rp

In [36]:
import seaborn as sns

In [37]:
df = sns.load_dataset("tips")

In [39]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [40]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [44]:
rp.summary_cont(df[["total_bill", "tip", "size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [46]:
rp.summary_cat(df[["sex", "smoker", "time","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4     time  Dinner    176    72.13
5            Lunch     68    27.87
6      day     Sat     87    35.66
7              Sun     76    31.15
8             Thur     62    25.41
9              Fri     19     7.79

In [50]:
df[["total_bill", "tip", "size"]].corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [52]:
df[["total_bill", "tip", "size"]].cov()

total_bill       tip      size
total_bill   79.252939  8.323502  5.065983
tip           8.323502  1.914455  0.643906
size          5.065983  0.643906  0.904591

# güven aralığı

In [56]:
import statsmodels.stats.api as sms

In [57]:
arr = np.random.randint(0,100,1000)
arr[0:10]

array([93, 32, 46, 10, 68, 69, 79, 87, 84, 92])

In [58]:
arr.mean()

49.701

In [59]:
sms.DescrStatsW(arr).tconfint_mean()

(47.89168316221326, 51.51031683778674)