In [1]:
import numpy as np

In [5]:
v = np.random.randint(0,10,5)
v

array([8, 4, 5, 3, 0])

In [6]:
np.sort(v)

array([0, 3, 4, 5, 8])

In [7]:
v

array([8, 4, 5, 3, 0])

In [8]:
v.sort()

In [9]:
v

array([0, 3, 4, 5, 8])

In [11]:
m =np.random.normal(20,5, (3,3))
m


array([[20.10254131, 11.59306592, 12.45765337],
       [ 8.46353855, 15.10088603, 25.09589782],
       [15.37999793, 16.34190648, 18.39512541]])

In [13]:
np.sort(m, axis = 1)

array([[11.59306592, 12.45765337, 20.10254131],
       [ 8.46353855, 15.10088603, 25.09589782],
       [15.37999793, 16.34190648, 18.39512541]])

satırları kendi içinde sıraladı

In [14]:
np.sort(m, axis = 0)

array([[ 8.46353855, 11.59306592, 12.45765337],
       [15.37999793, 15.10088603, 18.39512541],
       [20.10254131, 16.34190648, 25.09589782]])

sütunları sıraladı